application: csmh-ista
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
 
- url: /scripts
  static_dir: scripts
 
- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: artfinal.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
